app_friends/urls.py
from django.conf.urls import url
from .views import index,add_friends

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friends/$', add_friends, name='add_friends'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_statistics/urls.py
from django.conf.urls import url
from .views import index, change_background

urlpatterns = [
    url(r'^cbg/', change_background, name='change_background'),
    url(r'^$', index, name='index'),
]

app_status/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^add_status', add_status, name='add_status'),
]

tugas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_friends.urls as friends
import app_profile.urls as profile
import app_statistics.urls as statistics
import app_status.urls as status
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^friends/', include(friends, namespace='app_friends')),
    url(r'^profile/', include(profile, namespace='app_profile')),
    url(r'^statistics/', include(statistics, namespace='app_statistics')),
    url(r'^status/', include(status, namespace='app_status')),
    url(r'^$', RedirectView.as_view(url='/profile/', permanent=True))
]

app_friends/models.py
from django.db import models
from django.utils import timezone


class Friends(models.Model):
    name = models.CharField(max_length=140)
    created_date = models.DateTimeField(default = timezone.now)
    url = models.CharField(max_length=140)

app_profile/models.py
from django.db import models

# Create your models here.

app_statistics/models.py
from django.db import models

# Create your models here.

app_status/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
	status = models.CharField(max_length=140)
	created_date = models.DateTimeField(default = timezone.now)

	

app_friends/forms.py
from django import forms

class Friends_Form(forms.Form):

    
    st_attrs = {
        'type': 'text',
        'rows': 1, 
        'class': 'form-control',
        'placeholder':'Masukan nama teman..',
        'maxlength': 70,
        'size':5,
        'cols':150,
        'style':'resize:none',
    }
    url_attrs = {
        'type': 'text',
        'rows': 1,
        'class': 'form-control',
        'placeholder':'Masukkan url teman..',
        'maxlength': 70,
        'size':5,
        'cols':150,
        'style':'resize:none',

    }
    error_messages ={
        'required' : 'Isi ya namanya',
        'invalid' : 'url tidak ada'

    }

    name = forms.CharField(label='Nama', required=True, widget=forms.Textarea(attrs=st_attrs))
    url = forms.URLField(label='URL  ',initial='http://', required=True, widget=forms.Textarea(attrs=url_attrs))

app_status/forms.py
from django import forms

class Status_Form(forms.Form):
    st_attrs = {
        'type': 'text',
        'rows': 1,
        'class': 'form-control',
        'placeholder':'What is on your mind?',
        'maxlength': 70,
        'size':5,
        'cols':30,
        'style':'resize:none',
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=st_attrs))

app_friends/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friends_Form
from .models import Friends
from app_profile.views import user_name
from django.urls import reverse
import httplib2
import re

# Create your views here.
response = {}
def index(request):
    response = {
        'profile_name':user_name,
        'friends':Friends.objects.order_by('-created_date'),
        'friends_form':Friends_Form,
        'is_error':(request.GET.get('error', None) is not None),
    }
    return render(request, 'app_friends/friends_list.html', response)


def add_friends(request) :
    form = Friends_Form(request.POST or None)
    if request.method == 'POST' and form.is_valid() :
        if is_valid_url(request.POST['url']):
            Friends(name=request.POST['name'],url=request.POST['url']).save()
        else:
            return HttpResponseRedirect(reverse('app_friends:index') + "?error=1")
    else:
        return HttpResponseRedirect(reverse('app_friends:index') + "?error=1")
    return HttpResponseRedirect(reverse('app_friends:index'))


def is_valid_url(url):
    if not (re.match("^http://", url) or re.match("^https://", url)):
        url = "http://" + url
    try:
        h = httplib2.Http()
        resp = h.request(url, "HEAD")
        return int(resp[0]['status']) < 400
    except:
        return False

app_profile/views.py
from django.shortcuts import render

user_name = 'Yes Mi'
birth_date = '31 February 1999'
user_gender = 'Unidentified'
user_description = 'Am I even a human being'
user_mail = 'yes@mi.com'
expertises = ['I bark', 'I run', 'I lick']

bio_dict = [{'subject' : 'Birthday', 'value' : '  ' + birth_date},\
{'subject' : 'Gender', 'value' : '  ' + user_gender},\
{'subject' : 'Description', 'value' : '  ' + user_description},\
{'subject' : 'Email', 'value' : '  ' + user_mail},\
            ]


# Create your views here.
def index(request):
    response = {'bio_dict' : bio_dict, 'expertises' : expertises, 'user_name':user_name}
    return render(request, 'app_profile/app_profile.html', response)

app_statistics/views.py
from django.shortcuts import render
from app_friends.models import Friends
from app_status.models import Status
from app_profile.views import user_name
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    response = {
        'profile_name':user_name,
        'post_count':Status.objects.count(),
        'friend_count':Friends.objects.count(),
    }

    if response['post_count'] > 0:
        response['latest_post'] = Status.objects.order_by('-created_date')[0]

    return render(request, 'app_statistics/statistics.html', response)

def change_background(request):
    if (request.POST):
        response = HttpResponseRedirect(reverse('app_statistics:change_background'))
        response.set_cookie('bg-color', request.POST['bg-color'])
        return response
    else:
        return render(request, 'app_statistics/change_background.html', None)

app_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import Status_Form
from .models import Status
from app_profile.views import user_name


def index(request):
    response = {
        'profile_name':user_name,
        'status':Status.objects.order_by('-created_date'),
        'status_form':Status_Form
    }
    return render(request, 'app_status/status_list.html', response)


def add_status(request) :
    form = Status_Form(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        Status(status=request.POST['status']).save()

    return HttpResponseRedirect(reverse('app_status:index'))

app_friends/templates/app_friends/friends_list.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}
    Friends - Ling In
{% endblock %}

{% block additional_includes %}
    <link href="{% static 'css/app_friends.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section name="form" id="form">
        <div class="container">
            <form id="form" method="POST" action="{% url 'app_friends:add_friends' %}">
                <h2>Add Friends</h2>
                {% csrf_token %}
                {{ friends_form.as_p }}
                {% if is_error %}
                    <div class="alert alert-danger">
                        <b>Name must not be empty and URL must be accessible.</b>
                    </div>
                {% endif %}
                <input id="submit" type="submit" class="button" value="Submit">
                <br>
            </form>
        </div>
    </section>
    <section class ="friends" name="friends" id="friends-list">
        <div class="container">
            <h2 class="my-list-title">My Friends</h2>
            <div class="flex">
                {% for data in friends %}
                    <div class="flex-item">
                        <div class="friends-list">
                            <div class = "prof_photos">
                                <img src="{% static 'friend_profpict.png' %}" alt="image" border="0" style="width:60px;height:60px;">
                            </div>
                            <div class="friends-list-name">
                                {{data.name}}
                            </div>
                            <div class="friends-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="friends-list-url">
                                <a href= {{data.url}}>{{data.url}}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}  
     
    

   

app_friends/templates/app_friends/invalidURL.html
{% extends "templates/layout/base.html" %}

{% block content %}

<section name='form' id= 'input-list'>
    <br />
    <form id = 'form' method = 'GET' action='{% url 'app_friends:index' %}'>
        <div class='alert alert-danger text-center'>
            <strong> OOPS!</strong> URL yang kamu masukan tidak valid.
            </div>
            <button id='submit' type='submit' class='btn btn-default'> Back to Add add_friends
            </button>
        </form>

</section>
{% endblock %}

app_profile/templates/app_profile/app_profile.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}
    Profile - Ling In
{% endblock %}

{% block additional_includes %}
    <link rel="stylesheet" type="text/css" href="{% static "css/app_profile.css" %}"/>
{% endblock %}

{% block content %}

<div class="left_aligned">
    <h3>Profile</h3>
</div>
<div class="center_aligned">
    <img src="{% static 'profile_picture.png' %}" alt="Profile Picture" style="width:45%">
    <h4>{{ user_name }}</h4>
    <table align="center">
        {% for bio in bio_dict %}
         <tr>
             <td class="subject">{{ bio.subject }}</td>
             <td class="value">{{ bio.value }}</td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <table>
        <tr align="center" style="text-align: center;">
            <td class="expertise" colspan="{{ expertises|length }}">Expertise</td>
        </tr>
        <tr>
            {% for expertise in expertises %}
                <td class="expertise_value">{{ expertise }}</td>
            {% endfor %}
        </tr>
    </table>
    <br><br>
    <br><br>
</div>

{% endblock %}

app_statistics/templates/app_statistics/change_background.html
{% extends 'layout/base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
    Change Background Color - Ling In
{% endblock %}

{% block additional_includes %}
    <link href="{% static 'css/app_statistics.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="flex-container" style="margin-top:25%">
        <form id="form" method="POST" action="{% url 'app_statistics:change_background' %}">
            <h1 align="center">Change background color</h1>
            <h4 align="center">This is not supported in Internet Explorer 11 and earlier versions or Safari 9.1 and earlier versions.</h4>
            {% csrf_token %}
            <div class="profile">
                <input type="color" name="bg-color" value="#DEEAEA">
                <input type="submit" value="CHANGE ME COLOR">
            </div>
        </form>
    </div>
{% endblock %}

app_statistics/templates/app_statistics/statistics.html
{% extends 'layout/base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
    Statistics - Ling In
{% endblock %}

{% block additional_includes %}
    <link href="{% static 'css/app_statistics.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="flex-container">
        <div class="profile">
            <h1>
                <img src="{% static 'profile_picture.png' %}" style="width:4em">
                {{ profile_name }}
            </h1>
        </div>
        <div class="count-container">
            <div class="count-friends">
                {{ friend_count }} Friends
            </div>
            <div class="count-posts">
                {{ post_count }} Posts
            </div>
        </div>
        <div class="status-container">
             {% if post_count > 0%}
                 <div class="latest-post-text">
                     Latest post
                 </div>
                 <div class="status">{{ latest_post.status }}</div>
                 <div class="status-date">{{ latest_post.created_date }}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

app_status/templates/app_status/status_list.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}
    Status - Ling In
{% endblock %}

{% block additional_includes %}
    <link href="{% static 'css/app_status.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section name="form">
        <h2>Update Status</h2>
        <form id="form" method="POST" action="{% url 'app_status:add_status' %}">
            {% csrf_token %}
            {{ status_form }}
            <br>
            <button type="submit" class="btn btn-default" value="Post">Post</button>
        </form>
    </section>
    <section name = "list_status" id="list_status">
            {% for status in status %}
                <div class = "person">
                    <div class ="profile">
                        <div class = "prof_photos">
                            <img src="{% static 'profile_picture.png' %}" style="border-radius:100%" alt="Profile pictures" align="middle" height="42" width="50">
                        </div>
                        <div class = 'name'>
                                <p><b>{{ profile_name }}</b></p>
                        </div>
                    </div>
                        <div class = "status">
                            <div class="status-status">
                                {{ status.status }}
                            </div>
                            <div class="status-created-date">
                                {{ status.created_date }}
                            </div>
                        </div>
                </div>
            {% endfor %}
    </section>
{% endblock %}

templates/layout/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/tugas.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"><</script>

    {% block additional_includes %}

    {% endblock %}
    <title>
        {% block title %} Ling In {% endblock %}
    </title>
</head>
<body>
    <header>
        {% block header %}
            {% include 'partials/header.html' %}
        {% endblock %}
    </header>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        {% block footer %}
            {% include 'partials/footer.html' %}
        {% endblock %}
    </footer>


    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

<script type="application/javascript">
    $(document).ready(function() {
        if ($.cookie("bg-color"))
            document.body.style.backgroundColor = $.cookie("bg-color");
        else
            document.body.style.backgroundColor = "#DEEAEA";
    })
</script>

</html>

templates/partials/footer.html
<div class="footer-text">
    <p align="center">
        &copy; Made with &#9829; by Kelompok 5 PPW A.
        <a href="{% url 'app_statistics:change_background' %}">Feeling bored with your background color?</a>
    </p>
</div>

templates/partials/header.html
<!-- Fixed navbar -->
{% load staticfiles %}
{% load static %}
<nav class="navbar navbar-default navbar-static-top" style="background-color: aliceblue">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="/"><img style="width:4em" src="{% static 'logo.png'%}"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'app_profile:index' %}">Profile</a></li>
          <li><a href="{% url 'app_status:index' %}">Status</a></li>
          <li><a href="{% url 'app_friends:index' %}">Friends</a></li>
          <li><a href="{% url 'app_statistics:index' %}">Statistics</a></li>
      </ul>
    </div>
  </div>
</nav>